"""employlee table added

Revision ID: 08d82e7722ed
Revises: c55569b1c8b7
Create Date: 2026-02-02 16:21:24.747965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d82e7722ed'
down_revision: Union[str, Sequence[str], None] = 'c55569b1c8b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_grades_table',
    sa.Column('post_grade_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('post_grade_name', sa.String(), nullable=False),
    sa.Column('DateCreated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('post_grade_id'),
    sa.UniqueConstraint('post_grade_name')
    )
    op.create_index(op.f('ix_post_grades_table_post_grade_id'), 'post_grades_table', ['post_grade_id'], unique=False)
    op.create_table('employees',
    sa.Column('employee_Id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_number', sa.String(), nullable=False),
    sa.Column('fristname', sa.String(), nullable=False),
    sa.Column('middlename', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('post_number', sa.String(), nullable=True),
    sa.Column('job_title_id', sa.UUID(), nullable=False),
    sa.Column('post_title_id', sa.UUID(), nullable=False),
    sa.Column('post_grade_Id', sa.UUID(), nullable=False),
    sa.Column('divivision_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('DateCreated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['divivision_id'], ['divisions.division_id'], ),
    sa.ForeignKeyConstraint(['job_title_id'], ['job_titles_table.job_title_id'], ),
    sa.ForeignKeyConstraint(['post_grade_Id'], ['post_grades_table.post_grade_id'], ),
    sa.ForeignKeyConstraint(['post_title_id'], ['job_titles_table.job_title_id'], ),
    sa.PrimaryKeyConstraint('employee_Id'),
    sa.UniqueConstraint('employee_number')
    )
    op.create_index(op.f('ix_employees_employee_Id'), 'employees', ['employee_Id'], unique=False)
    op.add_column('job_titles_table', sa.Column('DateCreated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_titles_table', 'DateCreated')
    op.drop_index(op.f('ix_employees_employee_Id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_post_grades_table_post_grade_id'), table_name='post_grades_table')
    op.drop_table('post_grades_table')
    # ### end Alembic commands ###
