"""database init

Revision ID: 0b27f5d65323
Revises: 
Create Date: 2026-02-04 09:24:59.036142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b27f5d65323'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisions',
    sa.Column('division_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('division_name', sa.String(), nullable=False),
    sa.Column('DateCreated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('division_id'),
    sa.UniqueConstraint('division_name')
    )
    op.create_index(op.f('ix_divisions_division_id'), 'divisions', ['division_id'], unique=False)
    op.create_table('document_statuses_table',
    sa.Column('status_Id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('status_name', sa.String(), nullable=False),
    sa.Column('is_initial_status', sa.Boolean(), nullable=False),
    sa.Column('is_terminal_status', sa.Boolean(), nullable=False),
    sa.Column('DateCreated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('status_Id'),
    sa.UniqueConstraint('status_name')
    )
    op.create_index(op.f('ix_document_statuses_table_status_Id'), 'document_statuses_table', ['status_Id'], unique=False)
    op.create_table('job_titles_table',
    sa.Column('job_title_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_title_name', sa.String(), nullable=False),
    sa.Column('DateCreated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('job_title_id'),
    sa.UniqueConstraint('job_title_name')
    )
    op.create_index(op.f('ix_job_titles_table_job_title_id'), 'job_titles_table', ['job_title_id'], unique=False)
    op.create_table('post_grades_table',
    sa.Column('post_grade_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('post_grade_name', sa.String(), nullable=False),
    sa.Column('DateCreated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('post_grade_id'),
    sa.UniqueConstraint('post_grade_name')
    )
    op.create_index(op.f('ix_post_grades_table_post_grade_id'), 'post_grades_table', ['post_grade_id'], unique=False)
    op.create_table('users',
    sa.Column('user_Id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('user_role', sa.Enum('OD_DIRECTOR', 'OD_SECRETARY', 'OD_OFFICER', 'HRM', 'HRD', name='user_user_role'), nullable=False),
    sa.Column('fristname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('DateCreated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_Id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('employee_Table',
    sa.Column('employee_Id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_number', sa.String(), nullable=False),
    sa.Column('fristname', sa.String(), nullable=False),
    sa.Column('middlename', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('post_number', sa.String(), nullable=True),
    sa.Column('job_title_id', sa.UUID(), nullable=False),
    sa.Column('post_title_id', sa.UUID(), nullable=False),
    sa.Column('post_grade_Id', sa.UUID(), nullable=False),
    sa.Column('divivision_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('DateCreated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['divivision_id'], ['divisions.division_id'], ),
    sa.ForeignKeyConstraint(['job_title_id'], ['job_titles_table.job_title_id'], ),
    sa.ForeignKeyConstraint(['post_grade_Id'], ['post_grades_table.post_grade_id'], ),
    sa.ForeignKeyConstraint(['post_title_id'], ['job_titles_table.job_title_id'], ),
    sa.PrimaryKeyConstraint('employee_Id'),
    sa.UniqueConstraint('employee_number')
    )
    op.create_index(op.f('ix_employee_Table_employee_Id'), 'employee_Table', ['employee_Id'], unique=False)
    op.create_table('interim_evaluation_table',
    sa.Column('interimID', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_ID', sa.UUID(), nullable=False),
    sa.Column('period_of_evaluation', sa.String(), nullable=False),
    sa.Column('interim_submitted', sa.Boolean(), nullable=False),
    sa.Column('action_by_OD', sa.String(), nullable=True),
    sa.Column('document_path', sa.String(), nullable=False),
    sa.Column('submission_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_status', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=False),
    sa.Column('DateCreated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_Id'], ),
    sa.ForeignKeyConstraint(['employee_ID'], ['employee_Table.employee_Id'], ),
    sa.ForeignKeyConstraint(['processing_status'], ['document_statuses_table.status_Id'], ),
    sa.PrimaryKeyConstraint('interimID')
    )
    op.create_index(op.f('ix_interim_evaluation_table_interimID'), 'interim_evaluation_table', ['interimID'], unique=False)
    op.create_table('pers_table',
    sa.Column('per_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('period_of_evaluation', sa.String(), nullable=False),
    sa.Column('performance_scores', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pmas_scores', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('training_needs', sa.String(), nullable=True),
    sa.Column('CareerAspirations', sa.String(), nullable=True),
    sa.Column('RatingOfficerComments', sa.String(), nullable=True),
    sa.Column('DocumentShearePointLink', sa.String(), nullable=False),
    sa.Column('DateOfSubmission', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ProcessingSatus', sa.UUID(), nullable=False),
    sa.Column('AssignedTo', sa.UUID(), nullable=False),
    sa.Column('DateCreated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['AssignedTo'], ['users.user_Id'], ),
    sa.ForeignKeyConstraint(['ProcessingSatus'], ['document_statuses_table.status_Id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_Table.employee_Id'], ),
    sa.PrimaryKeyConstraint('per_id')
    )
    op.create_index(op.f('ix_pers_table_per_id'), 'pers_table', ['per_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pers_table_per_id'), table_name='pers_table')
    op.drop_table('pers_table')
    op.drop_index(op.f('ix_interim_evaluation_table_interimID'), table_name='interim_evaluation_table')
    op.drop_table('interim_evaluation_table')
    op.drop_index(op.f('ix_employee_Table_employee_Id'), table_name='employee_Table')
    op.drop_table('employee_Table')
    op.drop_table('users')
    op.drop_index(op.f('ix_post_grades_table_post_grade_id'), table_name='post_grades_table')
    op.drop_table('post_grades_table')
    op.drop_index(op.f('ix_job_titles_table_job_title_id'), table_name='job_titles_table')
    op.drop_table('job_titles_table')
    op.drop_index(op.f('ix_document_statuses_table_status_Id'), table_name='document_statuses_table')
    op.drop_table('document_statuses_table')
    op.drop_index(op.f('ix_divisions_division_id'), table_name='divisions')
    op.drop_table('divisions')
    # ### end Alembic commands ###
