"""work_plan table added

Revision ID: 42beaca99701
Revises: 0b27f5d65323
Create Date: 2026-02-04 10:44:56.425763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42beaca99701'
down_revision: Union[str, Sequence[str], None] = '0b27f5d65323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_plan_table',
    sa.Column('work_plan_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_ID', sa.UUID(), nullable=False),
    sa.Column('period_of_work_plan', sa.String(), nullable=False),
    sa.Column('work_plan_submited', sa.Boolean(), nullable=False),
    sa.Column('document_path', sa.String(), nullable=False),
    sa.Column('submission_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_status', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=False),
    sa.Column('DateCreated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_Id'], ),
    sa.ForeignKeyConstraint(['employee_ID'], ['employee_Table.employee_Id'], ),
    sa.ForeignKeyConstraint(['processing_status'], ['document_statuses_table.status_Id'], ),
    sa.PrimaryKeyConstraint('work_plan_id')
    )
    op.create_index(op.f('ix_work_plan_table_work_plan_id'), 'work_plan_table', ['work_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_plan_table_work_plan_id'), table_name='work_plan_table')
    op.drop_table('work_plan_table')
    # ### end Alembic commands ###
