"""Additional table added

Revision ID: 4433990a7c89
Revises: f8902e3226f2
Create Date: 2026-02-03 14:16:16.642018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4433990a7c89'
down_revision: Union[str, Sequence[str], None] = 'f8902e3226f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_statuses_table',
    sa.Column('status_Id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('status_name', sa.String(), nullable=False),
    sa.Column('is_initial_status', sa.Boolean(), nullable=False),
    sa.Column('is_terminal_status', sa.Boolean(), nullable=False),
    sa.Column('DateCreated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('status_Id'),
    sa.UniqueConstraint('status_name')
    )
    op.create_index(op.f('ix_document_statuses_table_status_Id'), 'document_statuses_table', ['status_Id'], unique=False)
    op.create_foreign_key(None, 'pers_table', 'document_statuses_table', ['ProcessingSatus'], ['status_Id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pers_table', type_='foreignkey')
    op.drop_index(op.f('ix_document_statuses_table_status_Id'), table_name='document_statuses_table')
    op.drop_table('document_statuses_table')
    # ### end Alembic commands ###
