"""more tables added

Revision ID: c55569b1c8b7
Revises: 1e4ccb4ca2f8
Create Date: 2026-02-02 15:50:19.552221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c55569b1c8b7'
down_revision: Union[str, Sequence[str], None] = '1e4ccb4ca2f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisions',
    sa.Column('division_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('division_name', sa.String(), nullable=False),
    sa.Column('DateCreated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('division_id'),
    sa.UniqueConstraint('division_name')
    )
    op.create_index(op.f('ix_divisions_division_id'), 'divisions', ['division_id'], unique=False)
    op.create_table('job_titles_table',
    sa.Column('job_title_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_title_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('job_title_id'),
    sa.UniqueConstraint('job_title_name')
    )
    op.create_index(op.f('ix_job_titles_table_job_title_id'), 'job_titles_table', ['job_title_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_titles_table_job_title_id'), table_name='job_titles_table')
    op.drop_table('job_titles_table')
    op.drop_index(op.f('ix_divisions_division_id'), table_name='divisions')
    op.drop_table('divisions')
    # ### end Alembic commands ###
