"""tables created

Revision ID: f8902e3226f2
Revises: 08d82e7722ed
Create Date: 2026-02-02 17:02:14.399290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8902e3226f2'
down_revision: Union[str, Sequence[str], None] = '08d82e7722ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pers_table',
    sa.Column('per_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('period_of_evaluation', sa.String(), nullable=False),
    sa.Column('performance_scores', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pmas_scores', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('training_needs', sa.String(), nullable=True),
    sa.Column('CareerAspirations', sa.String(), nullable=True),
    sa.Column('RatingOfficerComments', sa.String(), nullable=True),
    sa.Column('DocumentShearePointLink', sa.String(), nullable=False),
    sa.Column('DateOfSubmission', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ProcessingSatus', sa.UUID(), nullable=False),
    sa.Column('AssignedTo', sa.UUID(), nullable=False),
    sa.Column('DateCreated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['AssignedTo'], ['users.user_Id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_Id'], ),
    sa.PrimaryKeyConstraint('per_id')
    )
    op.create_index(op.f('ix_pers_table_per_id'), 'pers_table', ['per_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pers_table_per_id'), table_name='pers_table')
    op.drop_table('pers_table')
    # ### end Alembic commands ###
